version: '3.8'

services:
  frontend:
    build: ./
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - PORT=3002
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3002/api/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
